[tool.poetry]
name = "qwak-examples"
version = "0.1.0"
description = ""
authors = ["Guy Eshet <guye@qwak.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
langchain = "^0.0.315"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

