name: feature_set_quickstart_guide
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas=1.5.3
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - catboost
  - pip:
    - pyathena          # Athena query engine - required for working with the Feature Store
    - pyarrow<=12.0.1   # Apache Arrow library - required for working with the Feature Store
