name: bert_sentiment_analysis
channels:
  - defaults
  - conda-forge
  - huggingface
dependencies:
  - python=3.11
  - urllib3==1.26
  - pip
  - pytorch
  - transformers
  - accelerate
  - einops
  - xformers