[tool.poetry]
name = "sentence_embeddings"
version = "0.1.0"
description = ""
authors = ["Qwak <info@qwak.com>"]

[tool.poetry.dependencies]
python = ">=3.9.13,<3.10"
transformers = "^4.32.1"
sentence_transformers = "*"
accelerate = "*"
sentencepiece = "*"
pandas = "^2.2.2"
