[tool.poetry]
name = "falcon_7b"
version = "0.1.0"
description = ""
authors = ["Qwak <info@qwak.com>"]

[tool.poetry.dependencies]
python = ">=3.9.13,<3.10"
transformers = "^4.25.1"
sentence_transformers = "*"
accelerate = "^0.15.0"
sentencepiece = "^0.1.97"