[tool.poetry]
name = "sentence_embeddings"
version = "0.1.0"
description = ""
authors = ["Qwak <info@qwak.com>"]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
transformers = "*"
sentence_transformers = "*"
accelerate = "*"
sentencepiece = "*"
