[tool.poetry]
name = "t5_finetuned"
version = "0.1.0"
description = ""
authors = ["Qwak <info@qwak.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
pandas = "^1.3.5"
transformers = "^4.30.2"
accelerate = "^0.20.3"
xformers = "^0.0.20"
sentencepiece = "^0.1.99"
