name: gpt-neo-conda
channels:
  - defaults
  - conda-forge
  - huggingface
  - xformers
dependencies:
  - python=3.11
  - urllib3==1.26
  - pip
  - pytorch
  - transformers
  - accelerate
  - einops
  - xformers
