name: gpt-neo-conda
channels:
  - defaults
  - conda-forge
  - huggingface
  - pytorch
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=1.5.3
  - pip:
    - urllib3==1.26
  - pytorch::pytorch
  - transformers
