name: jfrog-ml-demo-gpt-fine-tuned
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=1.5.3
  - pip:
    - transformers==4.52.4
    - accelerate==1.8.1
    - datasets
    - peft==0.11.1
    - bitsandbytes
  - pytorch::pytorch
